org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.1
loader_version=0.19.3
loom_version=1.17.14
fabric_api_version=0.145.4+26.1.1
modmenu_version=18.0.0

mod_version=3.2.1+26.1.1-fabric
maven_group=net.lizistired
archives_base_name=cave_dust
