org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.13-beta

mod_id=cavedust
mod_name=Cave Dust Rethinking
mod_license=MPL-2.0
mod_version=3.3.1+26.3-neoforge
mod_group_id=net.lizistired.cavedust
